[package]
name = "tokio-maybe-tls"
version = "0.1.0"
authors = ["Jakob Schikowski"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Wrapper for plain or TLS streams"
keywords = ["tokio", "tls"]
categories = ["asynchronous", "network-programming"]
repository = "https://github.com/jakoschiko/tokio-maybe-tls"
edition = "2021"

[features]
native-tls = ["dep:tokio-native-tls"]
rustls = ["dep:tokio-rustls"]

[dependencies]
tokio = { version = "1.41.0", default-features = false }
tokio-native-tls = { version = "0.3.1", default-features = false, optional = true }
tokio-rustls = { version = "0.26.0", default-features = false, optional = true }

[dev-dependencies]
byte_string = "1.0.0"
rustls-native-certs = "0.8.0"
tokio = { version = "*", default-features = true, features = ["full"] }
tokio-maybe-tls = { path = ".", features = ["native-tls", "rustls"] }
tokio-native-tls = { version = "*", default-features = true }
tokio-rustls = { version = "*", default-features = true }
webpki-roots = "0.26.6"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
